import os

class Config:
    POSTGRES_RESERVATIONS_DBNAME = os.getenv("POSTGRES_RESERVATIONS_DBNAME", "reservations_v3")
    POSTGRES_RESERVATIONS_HOST = os.getenv("POSTGRES_RESERVATIONS_HOST", "localhost")
    POSTGRES_RESERVATIONS_USER = os.getenv("POSTGRES_RESERVATIONS_USER", "postgres")
    POSTGRES_RESERVATIONS_PASSWORD = os.getenv("POSTGRES_RESERVATIONS_PASSWORD", "postgres")
    POSTGRES_RESERVATIONS_PORT = os.getenv("POSTGRES_RESERVATIONS_PORT", "5432")

    SQLALCHEMY_DATABASE_URI = (
        f'postgresql+psycopg://{POSTGRES_RESERVATIONS_USER}:{POSTGRES_RESERVATIONS_PASSWORD}@{POSTGRES_RESERVATIONS_HOST}:{POSTGRES_RESERVATIONS_PORT}/{POSTGRES_RESERVATIONS_DBNAME}'
    )

    SQLALCHEMY_TRACK_MODIFICATIONS = False
    
    LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

    DEBUG_SERVER = os.getenv("DEBUG_SERVER", "False").lower() in ("true", "1", "t")

    SERVER_PORT = int(os.getenv("SERVER_PORT", 80))


    # Keycloak Konfiguration
    KEYCLOAK_HOST = os.getenv('KEYCLOAK_HOST', 'localhost:9090')
    KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM', 'biletado')
    
    KEYCLOAK_URL = f"http://{KEYCLOAK_HOST}/auth/realms/{KEYCLOAK_REALM}"